<a href="https://colab.research.google.com/github/a01770768-oss/JobishViri/blob/main/Clase_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
x = {'Company': ['Ford', 'Ford', 'VW', 'Audi', 'Audi', 'Ford'],
     'Price': [2, 3, 1, 2, 3, 1],
     'Weight': [4, 6, 2, 2, 4, None],
     'Length': [6, 7, 3, 6, 8, np.nan],
     'Made': ['China', 'Mexico', 'Mexico', 'Correa', 'UK', pd.NaT]
    }
df = pd.DataFrame(data = x)
df

  Company  Price  Weight  Length    Made
0    Ford      2     4.0     6.0   China
1    Ford      3     6.0     7.0  Mexico
2      VW      1     2.0     3.0  Mexico
3    Audi      2     2.0     6.0  Correa
4    Audi      3     4.0     8.0      UK
5    Ford      1     NaN     NaN     NaT

In [ ]:
pd.pivot_table(df[['Company', 'Price', 'Weight', 'Length']],
               index='Company'
              )

         Length  Price  Weight
Company
Audi        7.0    2.5     3.0
Ford        6.5    2.0     5.0
VW          3.0    1.0     2.0

In [ ]:
pd.pivot_table(df,
               index='Company',
               values = 'Price'
              )

         Price
Company
Audi       2.5
Ford       2.0
VW         1.0

In [ ]:
x = pd.pivot_table(df,
               index='Company',
               values='Price', # will do the average of each a, b, c, d
               aggfunc = 'sum',
               #aggfunc =  ['sum', 'mean', 'count'],
               margins = True
              )#.head()

In [ ]:
x

         Price
Company
Audi         5
Ford         6
VW           1
All         12

In [ ]:
x.index.name = None
x

      Price
Audi      5
Ford      6
VW        1
All      12

In [ ]:
df.groupby(['Company', 'Made'])[['Price']].sum()

                Price
Company Made
Audi    Correa      2
        UK          3
Ford    China       2
        Mexico      3
VW      Mexico      1

In [ ]:
df['Price'].mean()

np.float64(2.0)

In [ ]:
pd.pivot_table(df,
               index='Company',
               values=['Price','Weight'], # will do the average of each a, b, c, d
               aggfunc = 'sum',
               margins = True,
               columns = 'Made'
              )#.head()

        Price                        Weight
Made    China Correa Mexico   UK All  China Correa Mexico   UK   All
Company
Audi      NaN    2.0    NaN  3.0   5    NaN    2.0    NaN  4.0   6.0
Ford      2.0    NaN    3.0  NaN   5    4.0    NaN    6.0  NaN  10.0
VW        NaN    NaN    1.0  NaN   1    NaN    NaN    2.0  NaN   2.0
All       2.0    2.0    4.0  3.0  11    4.0    2.0    8.0  4.0  18.0

In [ ]:
x = {'Company': ['Ford', 'Ford', 'VW', 'Audi', 'Audi', 'Ford'],
     'Price': [2, 3, 1, 2, 3, 1],
     'Weight': [4, 6, 2, 2, 4, 3],
     'Length': [6, 9, 3, 6, 9, 3],
     'Made': ['China', 'Mexico', 'Mexico', 'China', 'China', 'China']
    }
df = pd.DataFrame(data = x)
df

  Company  Price  Weight  Length    Made
0    Ford      2       4       6   China
1    Ford      3       6       9  Mexico
2      VW      1       2       3  Mexico
3    Audi      2       2       6   China
4    Audi      3       4       9   China
5    Ford      1       3       3   China

In [ ]:
df

  Company  Price  Weight  Length    Made
0    Ford      2       4       6   China
1    Ford      3       6       9  Mexico
2      VW      1       2       3  Mexico
3    Audi      2       2       6   China
4    Audi      3       4       9   China
5    Ford      1       3       3   China

In [ ]:
pd.pivot_table(df,
               index='Company',
               values=['Price','Weight'], # will do the average of each a, b, c, d
               aggfunc={'Price': np.mean, 'Weight': np.sum},
               margins = True,
               margins_name='|*|Grand Total|*|',
               columns = 'Made'
              )#.head()

/tmp/ipykernel_752/1198496038.py:1: FutureWarning: The provided callable <function mean at 0x7b61a13722a0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df,
/tmp/ipykernel_752/1198496038.py:1: FutureWarning: The provided callable <function sum at 0x7b61a1370ea0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,
/tmp/ipykernel_752/1198496038.py:1: FutureWarning: The provided callable <function mean at 0x7b61a13722a0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df,
/tmp/ipykernel_752/1198496038.py:1: FutureWarning: The provided callable <function sum at 0x7b61a1370ea0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,
/tmp/ipykernel_752/1198496038.py:1: FutureWarning: The provided callable <function mean at 0x7b61a13722a0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df,
/tmp/ipykernel_752/1198496038.py:1: FutureWarning: The provided callable <function sum at 0x7b61a1370ea0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,

                  Price                          Weight         \
Made              China Mexico |*|Grand Total|*|  China Mexico
Company
Audi                2.5    NaN               2.5    6.0    NaN
Ford                1.5    3.0               2.0    7.0    6.0
VW                  NaN    1.0               1.0    NaN    2.0
|*|Grand Total|*|   2.0    2.0               2.0   13.0    8.0


Made              |*|Grand Total|*|
Company
Audi                              6
Ford                             13
VW                                2
|*|Grand Total|*|                21