<a href="https://colab.research.google.com/github/a01770768-oss/JobishViri/blob/main/Clase%206.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
df = sns.load_dataset('titanic')

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.groupby('sex')[['survived']].mean()

        survived
sex
female  0.742038
male    0.188908

In [ ]:
ndf = df.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack()
ndf.index.name = None
ndf

/tmp/ipykernel_577/1324084185.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ndf = df.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack()

class      First    Second     Third
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
ndf = df.pivot_table('survived',
               index='sex',
               columns='class'
               )
ndf

/tmp/ipykernel_577/1535367692.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  ndf = df.pivot_table('survived',

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
c = [1, 2, 2, 4, 5, 5, 5, 8, 9, 9, 9, 9]

In [ ]:
ccut = pd.cut(c, 3) #0.991 to  10 three bins
ccut

[(0.992, 3.667], (0.992, 3.667], (0.992, 3.667], (3.667, 6.333], (3.667, 6.333], ..., (6.333, 9.0], (6.333, 9.0], (6.333, 9.0], (6.333, 9.0], (6.333, 9.0]]
Length: 12
Categories (3, interval[float64, right]): [(0.992, 3.667] < (3.667, 6.333] < (6.333, 9.0]]

In [ ]:
ccut.value_counts()

(0.992, 3.667]    3
(3.667, 6.333]    4
(6.333, 9.0]      5
Name: count, dtype: int64

In [ ]:
ccut2=pd.cut(c,
             [0, 5, 10]
)
ccut2

[(0, 5], (0, 5], (0, 5], (0, 5], (0, 5], ..., (5, 10], (5, 10], (5, 10], (5, 10], (5, 10]]
Length: 12
Categories (2, interval[int64, right]): [(0, 5] < (5, 10]]

In [ ]:
cqcut = pd.qcut(c,3)
cqcut

[(0.999, 4.667], (0.999, 4.667], (0.999, 4.667], (0.999, 4.667], (4.667, 8.333], ..., (4.667, 8.333], (8.333, 9.0], (8.333, 9.0], (8.333, 9.0], (8.333, 9.0]]
Length: 12
Categories (3, interval[float64, right]): [(0.999, 4.667] < (4.667, 8.333] < (8.333, 9.0]]

In [ ]:
cqcut.value_counts()

(0.999, 4.667]    4
(4.667, 8.333]    4
(8.333, 9.0]      4
Name: count, dtype: int64

Multi-level pivot tables

In [ ]:
age = pd.cut(df['age'],
             [0, 18, 80] #specify the bin edges
             )
age

0      (18.0, 80.0]
1      (18.0, 80.0]
2      (18.0, 80.0]
3      (18.0, 80.0]
4      (18.0, 80.0]
           ...
886    (18.0, 80.0]
887    (18.0, 80.0]
888             NaN
889    (18.0, 80.0]
890    (18.0, 80.0]
Name: age, Length: 891, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 80]]

In [ ]:
age[0]

Interval(18, 80, closed='right')

In [ ]:
type[age]

type[0      (18.0, 80.0]
1      (18.0, 80.0]
2      (18.0, 80.0]
3      (18.0, 80.0]
4      (18.0, 80.0]
           ...
886    (18.0, 80.0]
887    (18.0, 80.0]
888             NaN
889    (18.0, 80.0]
890    (18.0, 80.0]
Name: age, Length: 891, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 80]]]

In [ ]:
age.value_counts()

age
(18, 80]    575
(0, 18]     139
Name: count, dtype: int64

In [ ]:
df.pivot_table('survived',
               ['sex', age], #index columns
               'class' #columns
               )

/tmp/ipykernel_577/1433048438.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table('survived',

class               First    Second     Third
sex    age
female (0, 18]   0.909091  1.000000  0.511628
       (18, 80]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 80]  0.375000  0.071429  0.133663

In [ ]:
fare = pd.qcut(df['fare'], 2)
fare

0       (-0.001, 14.454]
1      (14.454, 512.329]
2       (-0.001, 14.454]
3      (14.454, 512.329]
4       (-0.001, 14.454]
             ...
886     (-0.001, 14.454]
887    (14.454, 512.329]
888    (14.454, 512.329]
889    (14.454, 512.329]
890     (-0.001, 14.454]
Name: fare, Length: 891, dtype: category
Categories (2, interval[float64, right]): [(-0.001, 14.454] < (14.454, 512.329]]

In [ ]:
fare.value_counts()

fare
(-0.001, 14.454]     447
(14.454, 512.329]    444
Name: count, dtype: int64

In [ ]:
df.pivot_table('survived',
               ['sex', age],
               [fare, 'class']
               )

/tmp/ipykernel_577/2268592536.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table('survived',

fare            (-0.001, 14.454]                     (14.454, 512.329]  \
class                      First    Second     Third             First
sex    age
female (0, 18]               NaN  1.000000  0.714286          0.909091
       (18, 80]              NaN  0.880000  0.444444          0.972973
male   (0, 18]               NaN  0.000000  0.260870          0.800000
       (18, 80]              0.0  0.098039  0.125000          0.391304

fare
class              Second     Third
sex    age
female (0, 18]   1.000000  0.318182
       (18, 80]  0.914286  0.391304
male   (0, 18]   0.818182  0.178571
       (18, 80]  0.030303  0.192308

Extra Pivot Tables

In [ ]:
df.pivot_table(index = 'sex',
               columns = 'class',
               aggfunc = {'survived':sum,
                          'fare':'mean'
                          }
               )

/tmp/ipykernel_577/1345335190.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index = 'sex',
/tmp/ipykernel_577/1345335190.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(index = 'sex',

              fare                       survived
class        First     Second      Third    First Second Third
sex
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47

In [ ]:
df.pivot_table('survived',
               index='sex',
               columns='class',
               margins=True,
               margins_name = 'Total'
               )

/tmp/ipykernel_577/3014679834.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table('survived',

class      First    Second     Third     Total
sex
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
Total   0.629630  0.472826  0.242363  0.383838